### PR TITLE
Backend manager

### PR DESCRIPTION
**Pull request by davidzech**
Load cards from Parse database.

I'll be adding Unit Tests and UI Tests in the following days.

### CODE REVIEW

**Comment by davidzech** [comment]
Waiting for review from @ChaoticTempest

**Comment by ChaoticTempest** [comment]
It looks good. I still need to test it though.

**Comment by ChaoticTempest** [comment]
Tested. It primarily works. The images didn't load properly or were there any in the parse database to begin with?

**Comment by davidzech** [comment]
There aren't any images yet. I'm suspecting they won't be proportioned correctly at all.

**Comment by davidzech** [comment]
I'll fix the merge conflicts for this, then change the Query to grab categories instead.

**Comment by davidzech** [comment]
Categories is now the front: images work.

Image

**Pull request merged**
