### PR TITLE
Recipe finder

### PR DESCRIPTION
**Pull request by wongkevj**
Made one big async task in the recipelistfragment so it doesn't lag the UI.

### CODE REVIEW

**Comment by davidzech** [comment]
You dont need to register Parse Subclasses its done on launch

**Comment by ChaoticTempest** [comment]
Welp/ I didn't know you were fixing it. I already got my own version working with loading dialog and snackbar.

**Comment by wongkevj** [comment]
Oh. Uh... I guess if yours works better then pull that instead?

**Comment by ChaoticTempest** [comment]
Well, my version uses listeners to tell the recycler view that the asynctask has finished.

**Comment by wongkevj** [comment]
I think yours might be better design-wise, since I probably violated the SRP by having the fragment do everything, but I think I'd be able to polish up the recipe finder easier on mine. Your call, though.

**Comment by wongkevj** [comment]
Yeah, your code looks a lot better. I'll just close this one.

**Pull request closed without merging**
