### PR TITLE
Entry refactor

### PR DESCRIPTION
**Pull request by jimmyxgong**
Camera is implemented through camera Intent. There is a preview thumbnail in the activity. Pictures are saved in /storage/pictures/ folder, not in default android gallery. Feel free to change storage location. Also, spinner works on my phone but is at white text color; however, the spinner does not show the items in my emulator.

### CODE REVIEW

**Comment by davidzech** [comment]
Is this how it's supposed to look?
capture

**Comment by davidzech** [comment]
I think an actionbar should be present at the top of this activity as well.

**Comment by davidzech** [comment]
So I think we should wrap the current view in a Coordinator layout, add an actionbar, and move the cancel/done buttons to the action bar.

**Comment by jimmyxgong** [comment]
Ahh it looked fine on my phone. It's because I set the layout to match my phone's screen size. Not sure how to scale it with phones screen size

**Pull request merged**
